### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by zawnk** [spiotr12/board-game-geek#1]
I'm trying to use the lib in my small electron app, and on startup I get an error right away:

```
App threw an error during load
C:\projects\bgg\node_modules\@code-bucket\board-game-geek\index.js:1
export * from './dist';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:986:16)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\projects\bgg-likelihood\dist\index.js:39:25)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```
In my code I import it with `import { parseBggXmlApi2ThingResponse } from '@code-bucket/board-game-geek'` and then use the code from your first example. 

I'm using node v14.16.0.

Did a quick google and it seems like it is related to the way the stuff is exported in the index.js. Maybe [this response](https://stackoverflow.com/a/39436580) will be helpful and all you need to do is to add a single line to the package.json :)

**Comment by spiotr12** [comment]
I've update it. Try it now (v 0.2.2)

**Comment by zawnk** [comment]
Closer, but different error now :D 

```App threw an error during load
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\projects\bgg\node_modules\@code-bucket\board-game-geek\index.js
require() of ES modules is not supported.
require() of C:\projects\bgg\node_modules\@code-bucket\board-game-geek\index.js from C:\projects\bgg\dist\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename C:\projects\bgg\node_modules\@code-bucket\board-game-geek\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\projects\bgg\node_modules\@code-bucket\board-game-geek\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\projects\bgg\dist\index.js:39:25)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)`

**Comment by spiotr12** [comment]
I think this is a problem with your project. You need to use ESM as well, instead of CommonJS. I've tested in the project where I use it (angular, ts, node 14) it works fine (both, old and new solution worked).

**Comment by zawnk** [comment]
I mean you should be able to reproduce. All I did was set up a project with [electronforge](https://www.electronforge.io/templates/typescript-template) and then `npm i -S @code-bucket/board-game-geek@0.2.2` and I get that error when trying to do the first example in the `index.ts` file.

**Comment by spiotr12** [comment]
I think this is really your case: you need to use ES modules in your electron project, not the CommonJs. I'm pretty sure that is what you need to do. Check your configurations. You've asked me to make my lib the ES module, so I did. now you need to fix your code.

Sorry if i'm not that helpful, but I won't have time to reproduce it next few days.

**Comment by zawnk** [comment]
If I understand this issue correctly, there's not much I can do before April https://github.com/electron/electron/issues/21457

[This comment](https://github.com/electron/electron/issues/21457#issuecomment-784709147) says it should be fixed in Node in April. So I guess I have to wait.

**Comment by dsozzi** [comment]
Hi, sorry commenting again in this closed post but I have the same issue, actually, I'm trying to import the lib in my node project and it seems I can't find the correct way.

I've tried the following import statements

```import {parseBggXmlApi2ThingResponse} from "@code-bucket/board-game-geek/dist/utilities/parse-bgg-xml-api2-thing-response.js";```

```import {parseBggXmlApi2ThingResponse} from "@code-bucket/board-game-geek";```

but none is working

the first import returns
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\Users\USER\dev\app\node_modules\@code-bucket\board-game-geek\dist\models' is not supported resolving ES modules imported from C:\Users\USER\dev\app\node_modules\@code-bucket\board-game-geek\dist\utilities\parse-bgg-xml-api2-thing-response.js

the latter

 [DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json for C:\Users\USER\dev\app\node_modules\@code-bucket\board-game-geek\ resolving the main entry point "index.js", imported from C:\Users\USER\dev\app\index.js.
Default "index" lookups for the main are deprecated for ES modules.

In the documentation or example would be helpful if it's shown the correct import statement.

I'm using the latest node v19.5.0

thanks
